server:
  port: 8090
  
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:reservasdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      
      
